server:
  port: 8189
  servlet:
    context-path: /catalog-service
flyway:
  user: postgres
  password: 123
  schemas: catalog_db
  url: jdbc:postgresql://194.87.101.43:5432/catalog_db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://194.87.101.43:5432/catalog_db
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update


