server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: authorization-service
          uri: http://localhost:8187
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter
            - MyAuthFilter

        - id: cabinet-order-service
          uri: http://localhost:8192
          predicates:
            - Path=/cabinet/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cabinet-order-service
            - JwtAuthFilter
            - MyAuthFilter

        - id: cart-service
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service
            - JwtAuthFilter
            - MyAuthFilter

        - id: catalog-service
          uri: http://localhost:8189
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
            - PrefixPath=/catalog-service
            - JwtAuthFilter
            - MyAuthFilter




#jwt:
#  secret: v4V0pakg6p964nMkLm14HoV3uNZlEKqq9BLf7gShNPB4MjeE3fSjdoTvPQMg0nI7AG2w1UAImEAmP7Qy
#  lifetime: 36000000

