server:
  port: 8188
  servlet:
    context-path: /cabinet-order-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://194.87.101.43:5432/orders_db
    username: orders
    password: OrdersVideoteka2023
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  cart-service:
    url: http://localhost:8190/cart

