server:
  port: 8192
  servlet:
    context-path: /cabinet-order-service
flyway:
  user: orders
  password: OrdersVideoteka2023
  schemas: orders
  url: jdbc:postgresql://194.87.101.43:5432/orders_db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://194.87.101.43:5432/orders_db
    username: orders
    password: OrdersVideoteka2023
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
integrations:
  cart-service:
    url: http://localhost:8190/cart-service
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  catalog-service:
    url: http://localhost:8189/catalog-service
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
