server:
  port: 8190
  servlet:
    context-path: /cart-service
utils:
  cart:
    prefix: SPRING_WEB_APP_
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://194.87.101.43:5432/catalog_db
#    username: postgres
#    password: 123
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect