server:
  port: 8199
  servlet:
    context-path: /email-service
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: videotekahom@gmail.com
    password: etemmntjhoyjzxkq
#    TODO - 16-digits code!!!!
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
integrations:
  auth-service:
    url: http://localhost:8187/auth-service
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://194.87.101.43:5432/catalog_db
#    username: postgres
#    password: 123
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect